/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.GUI;

/**
 *
 * @author Adam
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fldWorkingDirSize = new javax.swing.JTextField();
        fldUserName = new javax.swing.JTextField();
        fldArchitecture = new javax.swing.JTextField();
        fldJavaVersion = new javax.swing.JTextField();
        fldWorkingDir = new javax.swing.JTextField();
        fldFreeSpace = new javax.swing.JTextField();
        fldAvailableSpace = new javax.swing.JTextField();
        fldTotalSpace = new javax.swing.JTextField();
        fldOsName = new javax.swing.JTextField();
        fldOsVersion = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblOsVersion = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblWorkingDir = new javax.swing.JLabel();
        lblOsName = new javax.swing.JLabel();
        lblWorkingDirSize = new javax.swing.JLabel();
        lblArchitecture = new javax.swing.JLabel();
        lblFreeSpace = new javax.swing.JLabel();
        lblJavaVersion = new javax.swing.JLabel();
        lblTotalSpace = new javax.swing.JLabel();
        lblAvailableSpace = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diagnostika");
        setMaximumSize(new java.awt.Dimension(561, 429));
        setMinimumSize(new java.awt.Dimension(561, 429));
        setPreferredSize(new java.awt.Dimension(733, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fldWorkingDirSize.setEditable(false);
        fldWorkingDirSize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldWorkingDirSize.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldWorkingDirSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 430, 30));

        fldUserName.setEditable(false);
        fldUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 430, 30));

        fldArchitecture.setEditable(false);
        fldArchitecture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldArchitecture.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldArchitecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 200, 30));

        fldJavaVersion.setEditable(false);
        fldJavaVersion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldJavaVersion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldJavaVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 430, 30));

        fldWorkingDir.setEditable(false);
        fldWorkingDir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldWorkingDir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldWorkingDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 430, 30));

        fldFreeSpace.setEditable(false);
        fldFreeSpace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldFreeSpace.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldFreeSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 430, 30));

        fldAvailableSpace.setEditable(false);
        fldAvailableSpace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldAvailableSpace.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldAvailableSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 430, 30));

        fldTotalSpace.setEditable(false);
        fldTotalSpace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldTotalSpace.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldTotalSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 430, 30));

        fldOsName.setEditable(false);
        fldOsName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldOsName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldOsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 30));

        fldOsVersion.setEditable(false);
        fldOsVersion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldOsVersion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fldOsVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 200, 30));

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(250, 250, 250));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Diagnostika");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setOpaque(true);
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        lblOsVersion.setBackground(new java.awt.Color(0, 0, 0));
        lblOsVersion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblOsVersion.setForeground(new java.awt.Color(250, 250, 250));
        lblOsVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOsVersion.setText("Verzia OS");
        lblOsVersion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblOsVersion.setOpaque(true);
        getContentPane().add(lblOsVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 200, 30));

        lblUserName.setBackground(new java.awt.Color(0, 0, 0));
        lblUserName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(250, 250, 250));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("Meno používateľa");
        lblUserName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUserName.setOpaque(true);
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 30));

        lblWorkingDir.setBackground(new java.awt.Color(0, 0, 0));
        lblWorkingDir.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblWorkingDir.setForeground(new java.awt.Color(250, 250, 250));
        lblWorkingDir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorkingDir.setText("Názov adresára");
        lblWorkingDir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblWorkingDir.setOpaque(true);
        getContentPane().add(lblWorkingDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, 30));

        lblOsName.setBackground(new java.awt.Color(0, 0, 0));
        lblOsName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblOsName.setForeground(new java.awt.Color(250, 250, 250));
        lblOsName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOsName.setText("Operačný systém(OS)");
        lblOsName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblOsName.setOpaque(true);
        getContentPane().add(lblOsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 30));

        lblWorkingDirSize.setBackground(new java.awt.Color(0, 0, 0));
        lblWorkingDirSize.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblWorkingDirSize.setForeground(new java.awt.Color(250, 250, 250));
        lblWorkingDirSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorkingDirSize.setText("Veľkosť adresára");
        lblWorkingDirSize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblWorkingDirSize.setOpaque(true);
        getContentPane().add(lblWorkingDirSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, 30));

        lblArchitecture.setBackground(new java.awt.Color(0, 0, 0));
        lblArchitecture.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblArchitecture.setForeground(new java.awt.Color(250, 250, 250));
        lblArchitecture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArchitecture.setText("Architektúra OS");
        lblArchitecture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblArchitecture.setOpaque(true);
        getContentPane().add(lblArchitecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 200, 30));

        lblFreeSpace.setBackground(new java.awt.Color(0, 0, 0));
        lblFreeSpace.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblFreeSpace.setForeground(new java.awt.Color(250, 250, 250));
        lblFreeSpace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFreeSpace.setText("Voľná pamäť pre JVM");
        lblFreeSpace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFreeSpace.setOpaque(true);
        getContentPane().add(lblFreeSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 200, 30));

        lblJavaVersion.setBackground(new java.awt.Color(0, 0, 0));
        lblJavaVersion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblJavaVersion.setForeground(new java.awt.Color(250, 250, 250));
        lblJavaVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJavaVersion.setText("Použitá verzia Javy");
        lblJavaVersion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblJavaVersion.setOpaque(true);
        getContentPane().add(lblJavaVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, 30));

        lblTotalSpace.setBackground(new java.awt.Color(0, 0, 0));
        lblTotalSpace.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTotalSpace.setForeground(new java.awt.Color(250, 250, 250));
        lblTotalSpace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalSpace.setText("Celková pamäť pre JVM");
        lblTotalSpace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTotalSpace.setOpaque(true);
        getContentPane().add(lblTotalSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 230, 30));

        lblAvailableSpace.setBackground(new java.awt.Color(0, 0, 0));
        lblAvailableSpace.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblAvailableSpace.setForeground(new java.awt.Color(250, 250, 250));
        lblAvailableSpace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvailableSpace.setText("Dostupná pamäť pre JVM");
        lblAvailableSpace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAvailableSpace.setOpaque(true);
        getContentPane().add(lblAvailableSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 440, -1, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stars.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 810, 600));
        background.getAccessibleContext().setAccessibleName("background");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    
    
    public void setFields(String osName, String osVersion, String architecture,
            String userName, String javaVersion, String currentDir, String currentDirSize,
            String heapSize, String freeHeapSize, String maxHeapSize){
        
        fldOsName.setText(osName);
        fldOsVersion.setText(osVersion);
        fldArchitecture.setText(architecture);
        fldUserName.setText(userName);
        fldJavaVersion.setText(javaVersion);
        fldWorkingDir.setText(currentDir);
        fldWorkingDirSize.setText(currentDirSize);
        fldTotalSpace.setText(maxHeapSize);
        fldAvailableSpace.setText(heapSize);
        fldFreeSpace.setText(freeHeapSize);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField fldArchitecture;
    private javax.swing.JTextField fldAvailableSpace;
    private javax.swing.JTextField fldFreeSpace;
    private javax.swing.JTextField fldJavaVersion;
    private javax.swing.JTextField fldOsName;
    private javax.swing.JTextField fldOsVersion;
    private javax.swing.JTextField fldTotalSpace;
    private javax.swing.JTextField fldUserName;
    private javax.swing.JTextField fldWorkingDir;
    private javax.swing.JTextField fldWorkingDirSize;
    private javax.swing.JLabel lblArchitecture;
    private javax.swing.JLabel lblAvailableSpace;
    private javax.swing.JLabel lblFreeSpace;
    private javax.swing.JLabel lblJavaVersion;
    private javax.swing.JLabel lblOsName;
    private javax.swing.JLabel lblOsVersion;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalSpace;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblWorkingDir;
    private javax.swing.JLabel lblWorkingDirSize;
    // End of variables declaration//GEN-END:variables
}
